import streamlit as st

from langchain_community.vectorstores import FAISS
from langchain_openai import OpenAIEmbeddings

from query_ygo_judge import ask_ygo_judge


APP_TITLE = "YGO Rule Expert - MVP"
DEFAULT_PROMPT = "Monster Reborn vs Solemn Judgment"
MAX_CONTEXT_CHARS = 1200

# Curated prompts that stress-test retrieval (cards, rules, injected Q&A).
HERO_CASES: tuple[tuple[str, str], ...] = (
    (
        "Damage Step",
        "At the start of the Damage Step, if my face-up Ally of Justice Catastor "
        "battles my opponent's face-up Neo-Spacian Grand Mole, what happens? "
        "Which effects apply and in what order?",
    ),
    (
        "Chain resolve",
        "My opponent activates Pot of Desires. I chain Ash Blossom & Joyous Spring. "
        "They chain Called by the Grave, banishing my Ash Blossom from the Graveyard. "
        "Walk through the chain: what resolves and in what order, and can I still "
        "negate Pot of Desires?",
    ),
    (
        "Genex + Q&A",
        '"Genex Ally Triforce" is Synchro Summoned using "Genex Ally Birdman" and '
        '"Elemental Mistress Doriado" as Synchro Materials. In that case, which "●" '
        'effects of "Genex Ally Triforce" will be applied?',
    ),
    (
        "Birdman return",
        'Can I activate "Genex Ally Birdman"\'s effect by returning a '
        '"Plaguespreader Zombie" or a "Battle Fader" that was Special Summoned by '
        "its own effect? If \"Degenerate Circuit\" is applying, can I activate "
        '"Genex Ally Birdman" or "Mist Valley Shaman"?',
    ),
    (
        "Simultaneous",
        "Two Trigger Effects would activate at the same time—one optional "
        '("if") and one mandatory ("when"). How do I build the chain if I control '
        "both monsters? Who chooses order?",
    ),
)

DISCLAIMER = (
    "This app is not from Konami or an official judge program. Answers use locally retrieved "
    "card and rule snippets and are generated by a language model; they may be incomplete or "
    "wrong. For official events, follow the head judge, the rulebook, and the KONAMI database."
)


@st.cache_resource(show_spinner=False)
def _get_cards_index_ntotal() -> int | None:
    try:
        store = FAISS.load_local(
            folder_path="faiss_cards_index",
            embeddings=OpenAIEmbeddings(model="text-embedding-3-small"),
            allow_dangerous_deserialization=True,
        )
        return int(store.index.ntotal)
    except Exception:
        return None


def _clip_text(text: str, max_chars: int = MAX_CONTEXT_CHARS) -> str:
    compact = " ".join(text.split())
    if len(compact) <= max_chars:
        return compact
    return compact[:max_chars].rstrip() + " ..."


def _card_heading(doc) -> str:
    meta = doc.metadata.get("card_name")
    if isinstance(meta, str) and meta.strip():
        return meta.strip()
    return "Card"


def _rule_heading(doc) -> str:
    rule_no = doc.metadata.get("rule_number")
    if isinstance(rule_no, str) and rule_no.strip():
        return f"Rule {rule_no.strip()}"
    title = doc.metadata.get("section_title")
    if isinstance(title, str) and title.strip():
        return title.strip()
    return "Rule passage"


def _render_context(result: dict) -> None:
    cards = result.get("cards", []) or []
    rules = result.get("rules", []) or []

    with st.expander("Retrieved context", expanded=True):
        st.caption(
            "Vector search results used for this answer. Snippets may be incomplete; check the "
            "original sources when it matters."
        )
        if not cards and not rules:
            st.caption("No snippets were retrieved.")
            return

        with st.expander(f"Card snippets ({len(cards)})", expanded=False):
            if not cards:
                st.caption("No card snippets.")
            for idx, doc in enumerate(cards, start=1):
                source = doc.metadata.get("source", "unknown_source")
                st.markdown(f"**[{idx}] {_card_heading(doc)}** · `{source}`")
                st.text(_clip_text(doc.page_content))

        with st.expander(f"Rule snippets ({len(rules)})", expanded=False):
            if not rules:
                st.caption("No rule snippets.")
            for idx, doc in enumerate(rules, start=1):
                source = doc.metadata.get("source", "unknown_source")
                gkind = doc.metadata.get("glossary_kind")
                extra = f" · {gkind}" if gkind else ""
                st.markdown(f"**[{idx}] {_rule_heading(doc)}** · `{source}`{extra}")
                st.text(_clip_text(doc.page_content))


def _answer_question(question: str) -> dict:
    return ask_ygo_judge(question=question)


def main() -> None:
    st.set_page_config(page_title=APP_TITLE, page_icon="🃏", layout="wide")
    st.title(APP_TITLE)
    st.info(DISCLAIMER)

    ntotal = _get_cards_index_ntotal()
    with st.sidebar:
        st.subheader("Knowledge base")
        if ntotal is not None:
            st.metric("Indexed cards", ntotal)
        else:
            st.metric(
                "Indexed cards",
                "N/A",
                help="Could not load faiss_cards_index (missing folder or corrupt files). Run preprocess_to_faiss.py first.",
            )
        st.caption("Set the OPENAI_API_KEY environment variable before asking questions.")

    if "messages" not in st.session_state:
        st.session_state.messages = []

    st.caption("Hero cases — click a button to send a showcase question:")
    hero_cols = st.columns(len(HERO_CASES))
    for i, col in enumerate(hero_cols):
        hero_label, hero_question = HERO_CASES[i]
        with col:
            if st.button(
                hero_label,
                key=f"hero_case_{i}",
                help=hero_question if len(hero_question) <= 280 else hero_question[:277] + "…",
            ):
                st.session_state.pending_question = hero_question

    for msg in st.session_state.messages:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])
            if msg["role"] == "assistant" and "context" in msg:
                _render_context(msg["context"])

    question = st.chat_input(f"Try: {DEFAULT_PROMPT}")
    pending = st.session_state.pop("pending_question", None)
    if pending is not None:
        question = pending
    elif not question:
        return

    st.session_state.messages.append({"role": "user", "content": question})
    with st.chat_message("user"):
        st.markdown(question)

    with st.chat_message("assistant"):
        with st.spinner("Thinking like a judge..."):
            try:
                result = _answer_question(question)
                answer = result.get("answer", "No answer returned.")
            except Exception as exc:  # pragma: no cover
                answer = f"Error: {exc}"
                result = {"cards": [], "rules": []}

        st.markdown(answer)
        _render_context(result)

    st.session_state.messages.append(
        {"role": "assistant", "content": answer, "context": result}
    )


if __name__ == "__main__":
    main()
